// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfiiq_g5ktvTBIvRoaYLjrWA_FuxgYgNg',
    appId: '1:422677040305:web:0722c877b4fe229c2d6690',
    messagingSenderId: '422677040305',
    projectId: 'tarea6-421618',
    authDomain: 'tarea6-421618.firebaseapp.com',
    storageBucket: 'tarea6-421618.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAHce8dOkeQgN85_1G-SZAIYmO2fImMUY',
    appId: '1:422677040305:android:f1ccf8dc333f5ccf2d6690',
    messagingSenderId: '422677040305',
    projectId: 'tarea6-421618',
    storageBucket: 'tarea6-421618.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ3JP8rN5tl79C7MlIoUROnm_5hDHSBJE',
    appId: '1:422677040305:ios:3bad48c959efff962d6690',
    messagingSenderId: '422677040305',
    projectId: 'tarea6-421618',
    storageBucket: 'tarea6-421618.appspot.com',
    iosBundleId: 'com.example.firebaseQuerys',
  );
}
